### ISSUE TITLE
layer: Simulating capabilities on Android can only be 92 bytes long, unable to set all capabilities.

### ISSUE THREAD

**Issue by ole-lie-arm** [KhronosGroup/Vulkan-Profiles#180]
Setting `debug.vulkan.khronos_profiles.simulate_capabilities SIMULATE_API_VERSION_BIT,SIMULATE_EXTENSIONS_BIT,SIMULATE_FEATURES_BIT,SIMULATE_PROPERTIES_BIT,SIMULATE_FORMATS_BIT `fails.

Error message: Value [...] is too long, 115 bytes vs a max of 92

**Comment by trevordblack** [comment]
Sorry for the late response. I've been out with a cold.

My understanding of this is that setting the layer settings on Android fails due to having the character limit exceed 92?
I'd need to dig in to find the specific reason that the character limit is 92.

Doesn't the `khronos_profiles.simulate_capabilities` default to `SIMULATE_API_VERSION_BIT,SIMULATE_EXTENSIONS_BIT,SIMULATE_FEATURES_BIT,SIMULATE_PROPERTIES_BIT,SIMULATE_FORMATS_BIT` when querying the Android Baseline 2021? As per https://vulkan.lunarg.com/doc/sdk/1.3.211.0/windows/profiles_layer.html

Is the problem that you're not trying to check ABP, and are just using an arbitrary profile?

**Comment by per-mathisen-arm** [comment]
@trevordblack According to the link you provided, and as far I can read the source, the default is just SIMULATE_API_VERSION_BIT, SIMULATE_FEATURES_BIT, SIMULATE_PROPERTIES_BIT. That is, missing extensions and formats. I hacked around this locally by adding a 'SIMULATE_ALL' capability.

**Comment by christophe-lunarg** [comment]
This issue is resolved with https://github.com/KhronosGroup/Vulkan-Profiles/pull/427 which introduces VK_EXT_layer_settings extension to setup programmatically the layer settings, particularly for Android. The extension is not yet published as we are implementing it in all Khronos layers first to test the design but you can try using it.
