### ISSUE TITLE
profile merge: Add format extensions supports

### ISSUE THREAD

**Issue by christophe-lunarg** [KhronosGroup/Vulkan-Profiles#237]
A profile specifying a format using VkFormatProperties2 or other extension structure can't be used with the merge script.

**Comment by werman** [comment]
This would be important for me, because without merging `VkFormatProperties3` I cannot use the merged capabilities with DXVK (which requires `VkFormatProperties3`).

**Comment by christophe-lunarg** [comment]
Ok, I'll investigate. But do yo need the merge script for DXVK? The schema supports `VkFormatProperties3`.

**Comment by christophe-lunarg** [comment]
Do you have your changes somewhere?

Out of curiousity, how are you using you merged profile with DXVK? That's to understand your use case for possible future development.

Thanks!

**Comment by werman** [comment]
https://github.com/werman/Vulkan-Profiles/commits/feature/VkFormatProperties3

> Out of curiousity, how are you using you merged profile with DXVK? That's to understand your use case for possible future development.

Long explanation: https://blogs.igalia.com/dpiliaiev/gfxreconstruct-test-mobile-gpus/

Shortexplanation:

I want an easy and quick way to test d3d9/d3d11/d3d12 games running through DXVK/VKD3D on Turnip driver (Mesa's VK driver or Adreno GPUs).

To do this I make gfxreconstruct capture on proper PC with Radeon GPU and replay the capture on dev board with Adreno GPU, so in order to make trace compatible, I use VK-Profiles to intersect these GPUs capabilities, then I capture the workload using the merged profile. This produces a capture that in most cases is compatible with both GPUs.

**Comment by christophe-lunarg** [comment]
Nice!

Thanks for sharing!
