### ISSUE TITLE
Missing extensions in schema (e.g. VK_NV_cuda_kernel_launch)

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Profiles#77]
I'm currently working on profile export from the Vulkan Hardware Database and I'm running into validation errors. One such example is the `VK_NV_cuda_kernel_launch` extensions. When exporting the JSON from a device that has this extension, the JSON does not validate against the schema:

Property 'VK_NV_cuda_kernel_launch' has not been defined and the schema does not allow additional properties.
Schema path:
https://schema.khronos.org/vulkan/profiles-1.3.203.json#/properties/capabilities/additionalProperties/properties/extensions/additionalProperties

So I was wondering how to handle these from a tooling point-of-view? Should the tool (in my case the database) skip export of extensions not defined in the schema or should the schema be changed so that all extensions can be included, no matter if defined or not in the schema. From the database' point-of-view I prefer the latter.

**Comment by aqnuep** [comment]
On a second thought, I think this restriction cannot be relaxed anyway, because the profiles solution relies on the `vk.xml` to determine whether a particular extension is an instance or device extension, hence whether the profiles library should pass it to `vkCreateInstance` or `vkCreateDevice`, thus in the current, joint extension list format used by the schema, it would be impossible to tell the type of unknown extensions.

**Comment by SaschaWillems** [comment]
Totally understandable. So for the reports, which are dynamically generated by the database, I'll parse the current schema and skip all extensions, features, properties, etc. that are not defined in there.
